version: "3"

services:

  nodejs:
    build:
      context: .
      target: debug
    command: npm start
    ports:
      - "3000:3000"
      - 9229:9229
    volumes:
      - .:/app/siceme
    depends_on:
      - postgresdb
    networks:
      - siceme-network
    links:
      -  postgresdb


  postgresdb:
    container_name: pg_container
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: "siceme123"
      POSTGRES_USER: root
      POSTGRES_DB: siceme
    ports:
    - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - siceme-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "siceme@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "siceme123"
    ports:
      - "5433:80"
    depends_on:
      - postgresdb
    networks:
      - siceme-network
    links:
      -  postgresdb
networks:
  siceme-network:
    driver: bridge
